### ISSUE TITLE
I go None for both CPU and GPU temp. 

### ISSUE THREAD

**Issue by rambo-yuanbo** [kethan1/WinTmp#1]
I go None for both CPU and GPU temp. 

>>> import WinTmp
>>> print(WinTmp.GPU_Temp())
None
>>>

Windows 10. 
12th Gen Intel(R) Core(TM) i5-12490F   3.00 GHz
Nvidia 1080 GPU.

thanks.

**Comment by kethan1** [comment]
I've pushed a new commit to this repo that uses LibreHardwareMonitor instead of OpenHardwareMonitor. Could you uninstall `WinTmp` and install it from the repo with `pip install git+https://github.com/kethan1/WinTmp.git`.

I'll try to get a new release published on PyPI soon too.

**Comment by kethan1** [comment]
Sorry for the long wait, but the package is now published on PyPI. Due to a lack of activity on this issue, I will be closing it. Please open another issue or comment on this one if further issues arise.
