### ISSUE TITLE
WinTmp.GPU_Temp() return None in Lenovo Legion GO

### ISSUE THREAD

**Issue by lollopasso00** [kethan1/WinTmp#3]
Hi, I tried this module to get the GPU temperature back, but it returns None. Anyone know how to solve it?
![Screenshot 2024-06-21 115253](https://github.com/kethan1/WinTmp/assets/39833218/23008d00-c998-4c5f-b668-878a9360ce33)

**Comment by kethan1** [comment]
What GPU does your computer have?

How to find the manufacturer and model: [https://www.microsoft.com/en-us/windows/learning-center/how-to-check-gpu](https://www.microsoft.com/en-us/windows/learning-center/how-to-check-gpu)

**Comment by lollopasso00** [comment]
Hi!
Thank you for the feedback.
