### ISSUE TITLE
GPU Temp showing "none" 

### ISSUE THREAD

**Issue by PaltroHos** [kethan1/WinTmp#4]
Hello, I am trying the command "print(WinTmp.GPU_Temp())" and get CPU temperature but GPU returns "None". My PC has a dedicated Nvidia RTX 3060 Ti

![Screenshot 2024-07-01 192147](https://github.com/kethan1/WinTmp/assets/174392982/fb51c160-49ae-4642-9e76-76d38671623d)

Help would be appreciated!
(Edit: it isn't about running the program as administrator, just had another issue with that but already resolved it but the problem is still the same)

**Comment by kethan1** [comment]
Thank you so much for using the library and sorry about now getting to this issue sooner. 

Does your GPU temperature show up when in the Task Manager under the performance tab? While CPU temps are usually never reported in this section, I have found that GPU temps usually appear under this section.

**Comment by PaltroHos** [comment]
Yes, also I'm on Windows 10 if that's relevant.

**Comment by kethan1** [comment]
I just published a new version of this library (v1.1.0) that uses the latest version of LibreHardwareMonitor. Could you try to install and test it out to see if it resolves your issue?

**Comment by PaltroHos** [comment]
Yes, I updated the version and now it works! Thanks.
